/** \file
 *  This C header file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : D:\\message\\Message.g
 *     -                            On : 2013-08-30 12:48:29
 *     -                 for the lexer : MessageLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer MessageLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pMessageLexer, which is returned from a call to MessageLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pMessageLexer are  as follows:
 *
 *  -  void      pMessageLexer->T__24(pMessageLexer)
 *  -  void      pMessageLexer->T__25(pMessageLexer)
 *  -  void      pMessageLexer->T__26(pMessageLexer)
 *  -  void      pMessageLexer->T__27(pMessageLexer)
 *  -  void      pMessageLexer->T__28(pMessageLexer)
 *  -  void      pMessageLexer->T__29(pMessageLexer)
 *  -  void      pMessageLexer->T__30(pMessageLexer)
 *  -  void      pMessageLexer->T__31(pMessageLexer)
 *  -  void      pMessageLexer->T__32(pMessageLexer)
 *  -  void      pMessageLexer->ENUM(pMessageLexer)
 *  -  void      pMessageLexer->FIELD(pMessageLexer)
 *  -  void      pMessageLexer->FIELD_ENUM(pMessageLexer)
 *  -  void      pMessageLexer->FIELD_DEFAULT(pMessageLexer)
 *  -  void      pMessageLexer->ARRAY(pMessageLexer)
 *  -  void      pMessageLexer->STRUCT(pMessageLexer)
 *  -  void      pMessageLexer->MESSAGE(pMessageLexer)
 *  -  void      pMessageLexer->INCLUDE(pMessageLexer)
 *  -  void      pMessageLexer->PACKAGES(pMessageLexer)
 *  -  void      pMessageLexer->LQUO(pMessageLexer)
 *  -  void      pMessageLexer->LBRACKET(pMessageLexer)
 *  -  void      pMessageLexer->ENABLEIF(pMessageLexer)
 *  -  void      pMessageLexer->FORWARD(pMessageLexer)
 *  -  void      pMessageLexer->TYPEDEF(pMessageLexer)
 *  -  void      pMessageLexer->OP(pMessageLexer)
 *  -  void      pMessageLexer->ID(pMessageLexer)
 *  -  void      pMessageLexer->PATH(pMessageLexer)
 *  -  void      pMessageLexer->INT(pMessageLexer)
 *  -  void      pMessageLexer->COMMENT(pMessageLexer)
 *  -  void      pMessageLexer->WS(pMessageLexer)
 *  -  void      pMessageLexer->Tokens(pMessageLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MessageLexer_H
#define _MessageLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct MessageLexer_Ctx_struct MessageLexer, * pMessageLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for MessageLexer
 */
struct MessageLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__24)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__25)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__26)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__27)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__28)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__29)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__30)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__31)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mT__32)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mENUM)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mFIELD)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mFIELD_ENUM)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mFIELD_DEFAULT)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mARRAY)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mSTRUCT)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mMESSAGE)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mINCLUDE)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mPACKAGES)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mLQUO)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mLBRACKET)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mENABLEIF)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mFORWARD)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mTYPEDEF)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mOP)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mID)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mPATH)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mINT)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mWS)	(struct MessageLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct MessageLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct MessageLexer_Ctx_struct * ctx);
    void	    (*free)   (struct MessageLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pMessageLexer MessageLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pMessageLexer MessageLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define EOF      -1
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define FORWARD      4
#define ENUM      5
#define ID      6
#define STRUCT      7
#define COMMENT      8
#define TYPEDEF      9
#define PACKAGES      10
#define PATH      11
#define INCLUDE      12
#define MESSAGE      13
#define ENABLEIF      14
#define OP      15
#define INT      16
#define FIELD      17
#define FIELD_ENUM      18
#define FIELD_DEFAULT      19
#define ARRAY      20
#define LQUO      21
#define LBRACKET      22
#define WS      23
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for MessageLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
