/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : D:\\message\\ParseXml.g
 *     -                            On : 2013-10-24 15:01:37
 *     -                 for the lexer : ParseXmlLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ParseXmlLexer.h"
/* ----------------------------------------- */


/** String literals used by ParseXmlLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x65, 0x6E, 0x75, 0x6D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x65, 0x6E, 0x75, 0x6D, 0x5F, 0x66, 0x69, 0x65, 0x6C, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x63, 0x6C, 0x61, 0x73, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x41, 0x72, 0x72, 0x61, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x66, 0x69, 0x65, 0x6C, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x70, 0x72, 0x6F, 0x70, 0x65, 0x72, 0x74, 0x79,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};




/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pParseXmlLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pParseXmlLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pParseXmlLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pParseXmlLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

 
/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER		    
#undef	    RULEMEMO		    
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar)) 
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif
#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */


/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE  void	mT__18    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT__19    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT__20    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT__21    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_ENUM    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_ENUM_FIELD    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_STRUCT    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_CLASS    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_ARRAY    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_FIELD    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_PROPERTY    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_ID    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_INT    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_PROP_STRING    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_PROPERPTY_BEGIN    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_PROPERPTY_END    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_COMMENT    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mT_WS    (pParseXmlLexer ctx);
static ANTLR3_INLINE  void	mTokens    (pParseXmlLexer ctx);
static void	ParseXmlLexerFree(pParseXmlLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ParseXmlLexerFree  (pParseXmlLexer ctx)
{
    LEXER->free(LEXER);
    
    ANTLR3_FREE(ctx);
}

static void
ParseXmlLexerReset (pParseXmlLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "D:\\message\\ParseXml.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ParseXmlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return 
 *     - Success pParseXmlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pParseXmlLexer ParseXmlLexerNew         
(pANTLR3_INPUT_STREAM instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ParseXmlLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ParseXmlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return 
 *     - Success pParseXmlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pParseXmlLexer ParseXmlLexerNewSSD         
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pParseXmlLexer ctx; // Context structure we will build and return

    ctx = (pParseXmlLexer) ANTLR3_CALLOC(1, sizeof(ParseXmlLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in ParseXmlLexer.h here so you can get a sense
     * of what goes where.
     */
    
    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);
    
    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ParseXmlLexer interface
     */
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT_ENUM	= mT_ENUM;
    ctx->mT_ENUM_FIELD	= mT_ENUM_FIELD;
    ctx->mT_STRUCT	= mT_STRUCT;
    ctx->mT_CLASS	= mT_CLASS;
    ctx->mT_ARRAY	= mT_ARRAY;
    ctx->mT_FIELD	= mT_FIELD;
    ctx->mT_PROPERTY	= mT_PROPERTY;
    ctx->mT_ID	= mT_ID;
    ctx->mT_INT	= mT_INT;
    ctx->mT_PROP_STRING	= mT_PROP_STRING;
    ctx->mT_PROPERPTY_BEGIN	= mT_PROPERPTY_BEGIN;
    ctx->mT_PROPERPTY_END	= mT_PROPERPTY_END;
    ctx->mT_COMMENT	= mT_COMMENT;
    ctx->mT_WS	= mT_WS;
    ctx->mTokens	= mTokens;
    
    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;
    
    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);
    
    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ParseXmlLexerFree;
    ctx->reset          = ParseXmlLexerReset;

    
    


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
 

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;
       
    
    // D:\\message\\ParseXml.g:7:7: ( '{' )
    // D:\\message\\ParseXml.g:7:9: '{'
    {
        MATCHC('{'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 8:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;
       
    
    // D:\\message\\ParseXml.g:8:7: ( '}' )
    // D:\\message\\ParseXml.g:8:9: '}'
    {
        MATCHC('}'); 
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 9:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;
       
    
    // D:\\message\\ParseXml.g:9:7: ( '=' )
    // D:\\message\\ParseXml.g:9:9: '='
    {
        MATCHC('='); 
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 10:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;
       
    
    // D:\\message\\ParseXml.g:10:7: ( ',' )
    // D:\\message\\ParseXml.g:10:9: ','
    {
        MATCHC(','); 
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 73:8: ( 'enum' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_ENUM
 *
 * Looks to match the characters the constitute the token T_ENUM
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_ENUM(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_ENUM;
       
    
    // D:\\message\\ParseXml.g:73:8: ( 'enum' )
    // D:\\message\\ParseXml.g:74:2: 'enum'
    {
        MATCHS(lit_1); 
        if  (HASEXCEPTION())
        {
            goto ruleT_ENUMEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_ENUMEx; /* Prevent compiler warnings */
    ruleT_ENUMEx: ;

}
// $ANTLR end T_ENUM

//   Comes from: 78:2: ( 'enum_field' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_ENUM_FIELD
 *
 * Looks to match the characters the constitute the token T_ENUM_FIELD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_ENUM_FIELD(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_ENUM_FIELD;
       
    
    // D:\\message\\ParseXml.g:78:2: ( 'enum_field' )
    // D:\\message\\ParseXml.g:79:2: 'enum_field'
    {
        MATCHS(lit_2); 
        if  (HASEXCEPTION())
        {
            goto ruleT_ENUM_FIELDEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_ENUM_FIELDEx; /* Prevent compiler warnings */
    ruleT_ENUM_FIELDEx: ;

}
// $ANTLR end T_ENUM_FIELD

//   Comes from: 82:9: ( 'struct' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_STRUCT
 *
 * Looks to match the characters the constitute the token T_STRUCT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_STRUCT(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_STRUCT;
       
    
    // D:\\message\\ParseXml.g:82:9: ( 'struct' )
    // D:\\message\\ParseXml.g:83:2: 'struct'
    {
        MATCHS(lit_3); 
        if  (HASEXCEPTION())
        {
            goto ruleT_STRUCTEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_STRUCTEx; /* Prevent compiler warnings */
    ruleT_STRUCTEx: ;

}
// $ANTLR end T_STRUCT

//   Comes from: 86:9: ( 'class' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_CLASS
 *
 * Looks to match the characters the constitute the token T_CLASS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_CLASS(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_CLASS;
       
    
    // D:\\message\\ParseXml.g:86:9: ( 'class' )
    // D:\\message\\ParseXml.g:87:2: 'class'
    {
        MATCHS(lit_4); 
        if  (HASEXCEPTION())
        {
            goto ruleT_CLASSEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_CLASSEx; /* Prevent compiler warnings */
    ruleT_CLASSEx: ;

}
// $ANTLR end T_CLASS

//   Comes from: 90:9: ( 'Array' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_ARRAY
 *
 * Looks to match the characters the constitute the token T_ARRAY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_ARRAY(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_ARRAY;
       
    
    // D:\\message\\ParseXml.g:90:9: ( 'Array' )
    // D:\\message\\ParseXml.g:91:2: 'Array'
    {
        MATCHS(lit_5); 
        if  (HASEXCEPTION())
        {
            goto ruleT_ARRAYEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_ARRAYEx; /* Prevent compiler warnings */
    ruleT_ARRAYEx: ;

}
// $ANTLR end T_ARRAY

//   Comes from: 95:2: ( 'field' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_FIELD
 *
 * Looks to match the characters the constitute the token T_FIELD
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_FIELD(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_FIELD;
       
    
    // D:\\message\\ParseXml.g:95:2: ( 'field' )
    // D:\\message\\ParseXml.g:96:2: 'field'
    {
        MATCHS(lit_6); 
        if  (HASEXCEPTION())
        {
            goto ruleT_FIELDEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_FIELDEx; /* Prevent compiler warnings */
    ruleT_FIELDEx: ;

}
// $ANTLR end T_FIELD

//   Comes from: 100:2: ( 'property' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_PROPERTY
 *
 * Looks to match the characters the constitute the token T_PROPERTY
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_PROPERTY(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_PROPERTY;
       
    
    // D:\\message\\ParseXml.g:100:2: ( 'property' )
    // D:\\message\\ParseXml.g:101:2: 'property'
    {
        MATCHS(lit_7); 
        if  (HASEXCEPTION())
        {
            goto ruleT_PROPERTYEx;
        }



    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_PROPERTYEx; /* Prevent compiler warnings */
    ruleT_PROPERTYEx: ;

}
// $ANTLR end T_PROPERTY

//   Comes from: 104:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_ID
 *
 * Looks to match the characters the constitute the token T_ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_ID(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_ID;
       
    
    // D:\\message\\ParseXml.g:104:7: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // D:\\message\\ParseXml.g:104:9: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleT_IDEx;
        }


        // D:\\message\\ParseXml.g:104:33: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) ) 
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1) 
            {
        	case 1:
        	    // D:\\message\\ParseXml.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleT_IDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_IDEx; /* Prevent compiler warnings */
    ruleT_IDEx: ;

}
// $ANTLR end T_ID

//   Comes from: 107:7: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_INT
 *
 * Looks to match the characters the constitute the token T_INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_INT(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_INT;
       
    
    // D:\\message\\ParseXml.g:107:7: ( ( '0' .. '9' )+ )
    // D:\\message\\ParseXml.g:107:9: ( '0' .. '9' )+
    {
        // D:\\message\\ParseXml.g:107:9: ( '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( LA(1) ) 
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2) 
        	{
        	    case 1:
        	        // D:\\message\\ParseXml.g:107:9: '0' .. '9'
        	        {
        	            MATCHRANGE('0', '9'); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto ruleT_INTEx;
        	            }


        	        }
        	        break;

        	    default:
        	    
        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleT_INTEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_INTEx; /* Prevent compiler warnings */
    ruleT_INTEx: ;

}
// $ANTLR end T_INT

//   Comes from: 111:2: ( '\"' (~ ( '\"' ) )* '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_PROP_STRING
 *
 * Looks to match the characters the constitute the token T_PROP_STRING
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_PROP_STRING(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_PROP_STRING;
       
    
    // D:\\message\\ParseXml.g:111:2: ( '\"' (~ ( '\"' ) )* '\"' )
    // D:\\message\\ParseXml.g:112:2: '\"' (~ ( '\"' ) )* '\"'
    {
        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleT_PROP_STRINGEx;
        }


        // D:\\message\\ParseXml.g:112:6: (~ ( '\"' ) )*

        for (;;)
        {
            int alt3=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = LA(1);
                if ( (((LA3_0 >= 0x0000) && (LA3_0 <= '!')) || ((LA3_0 >= '#') && (LA3_0 <= 0xFFFF)))) 
                {
                    alt3=1;
                }

            }
            switch (alt3) 
            {
        	case 1:
        	    // D:\\message\\ParseXml.g:112:6: ~ ( '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleT_PROP_STRINGEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */

        MATCHC('"'); 
        if  (HASEXCEPTION())
        {
            goto ruleT_PROP_STRINGEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_PROP_STRINGEx; /* Prevent compiler warnings */
    ruleT_PROP_STRINGEx: ;

}
// $ANTLR end T_PROP_STRING

//   Comes from: 116:2: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_PROPERPTY_BEGIN
 *
 * Looks to match the characters the constitute the token T_PROPERPTY_BEGIN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_PROPERPTY_BEGIN(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_PROPERPTY_BEGIN;
       
    
    // D:\\message\\ParseXml.g:116:2: ( '[' )
    // D:\\message\\ParseXml.g:117:2: '['
    {
        MATCHC('['); 
        if  (HASEXCEPTION())
        {
            goto ruleT_PROPERPTY_BEGINEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_PROPERPTY_BEGINEx; /* Prevent compiler warnings */
    ruleT_PROPERPTY_BEGINEx: ;

}
// $ANTLR end T_PROPERPTY_BEGIN

//   Comes from: 120:2: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_PROPERPTY_END
 *
 * Looks to match the characters the constitute the token T_PROPERPTY_END
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_PROPERPTY_END(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_PROPERPTY_END;
       
    
    // D:\\message\\ParseXml.g:120:2: ( ']' )
    // D:\\message\\ParseXml.g:121:2: ']'
    {
        MATCHC(']'); 
        if  (HASEXCEPTION())
        {
            goto ruleT_PROPERPTY_ENDEx;
        }


    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_PROPERPTY_ENDEx; /* Prevent compiler warnings */
    ruleT_PROPERPTY_ENDEx: ;

}
// $ANTLR end T_PROPERPTY_END

//   Comes from: 125:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_COMMENT
 *
 * Looks to match the characters the constitute the token T_COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_COMMENT(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_COMMENT;
       
    
    // D:\\message\\ParseXml.g:125:5: ( '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n' )
    // D:\\message\\ParseXml.g:125:9: '//' (~ ( '\\n' | '\\r' ) )* ( '\\r' )? '\\n'
    {
        MATCHS(lit_8); 
        if  (HASEXCEPTION())
        {
            goto ruleT_COMMENTEx;
        }



        // D:\\message\\ParseXml.g:125:14: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt4=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA4_0 = LA(1);
                if ( (((LA4_0 >= 0x0000) && (LA4_0 <= '\t')) || ((LA4_0 >= 0x000B) && (LA4_0 <= '\f')) || ((LA4_0 >= 0x000E) && (LA4_0 <= 0xFFFF)))) 
                {
                    alt4=1;
                }

            }
            switch (alt4) 
            {
        	case 1:
        	    // D:\\message\\ParseXml.g:125:14: ~ ( '\\n' | '\\r' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();

        	        }
        	        else 
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();    goto ruleT_COMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop4;	/* break out of the loop */
        	    break;
            }
        }
        loop4: ; /* Jump out to here if this rule does not match */


        // D:\\message\\ParseXml.g:125:28: ( '\\r' )?
        {
            int alt5=2;
            switch ( LA(1) ) 
            {
                case '\r':
                	{
                		alt5=1;
                	}
                    break;
            }

            switch (alt5) 
            {
        	case 1:
        	    // D:\\message\\ParseXml.g:125:28: '\\r'
        	    {
        	        MATCHC('\r'); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleT_COMMENTEx;
        	        }


        	    }
        	    break;

            }
        }
        MATCHC('\n'); 
        if  (HASEXCEPTION())
        {
            goto ruleT_COMMENTEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_COMMENTEx; /* Prevent compiler warnings */
    ruleT_COMMENTEx: ;

}
// $ANTLR end T_COMMENT

//   Comes from: 128:7: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T_WS
 *
 * Looks to match the characters the constitute the token T_WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT_WS(pParseXmlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T_WS;
       
    
    // D:\\message\\ParseXml.g:128:7: ( ( ' ' | '\\t' | '\\r' | '\\n' ) )
    // D:\\message\\ParseXml.g:128:11: ( ' ' | '\\t' | '\\r' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        {
            CONSUME();

        }
        else 
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();    goto ruleT_WSEx;
        }

        {
            LEXSTATE->channel=HIDDEN;
        }

    }

	LEXSTATE->type = _type;

    // This is where rules clean up and exit
    //
    goto ruleT_WSEx; /* Prevent compiler warnings */
    ruleT_WSEx: ;

}
// $ANTLR end T_WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void 
mTokens(pParseXmlLexer ctx)
{
    {
        //  D:\\message\\ParseXml.g:1:8: ( T__18 | T__19 | T__20 | T__21 | T_ENUM | T_ENUM_FIELD | T_STRUCT | T_CLASS | T_ARRAY | T_FIELD | T_PROPERTY | T_ID | T_INT | T_PROP_STRING | T_PROPERPTY_BEGIN | T_PROPERPTY_END | T_COMMENT | T_WS )
        
        ANTLR3_UINT32 alt6;

        alt6=18;

        switch ( LA(1) ) 
        {
        case '{':
        	{
        		alt6=1;
        	}
            break;
        case '}':
        	{
        		alt6=2;
        	}
            break;
        case '=':
        	{
        		alt6=3;
        	}
            break;
        case ',':
        	{
        		alt6=4;
        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'n':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'u':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'm':
        							{
        								switch ( LA(5) ) 
        								{
        								case '_':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'f':
        											{
        												switch ( LA(7) ) 
        												{
        												case 'i':
        													{
        														switch ( LA(8) ) 
        														{
        														case 'e':
        															{
        																switch ( LA(9) ) 
        																{
        																case 'l':
        																	{
        																		switch ( LA(10) ) 
        																		{
        																		case 'd':
        																			{
        																				switch ( LA(11) ) 
        																				{
        																				case '0':
        																				case '1':
        																				case '2':
        																				case '3':
        																				case '4':
        																				case '5':
        																				case '6':
        																				case '7':
        																				case '8':
        																				case '9':
        																				case 'A':
        																				case 'B':
        																				case 'C':
        																				case 'D':
        																				case 'E':
        																				case 'F':
        																				case 'G':
        																				case 'H':
        																				case 'I':
        																				case 'J':
        																				case 'K':
        																				case 'L':
        																				case 'M':
        																				case 'N':
        																				case 'O':
        																				case 'P':
        																				case 'Q':
        																				case 'R':
        																				case 'S':
        																				case 'T':
        																				case 'U':
        																				case 'V':
        																				case 'W':
        																				case 'X':
        																				case 'Y':
        																				case 'Z':
        																				case '_':
        																				case 'a':
        																				case 'b':
        																				case 'c':
        																				case 'd':
        																				case 'e':
        																				case 'f':
        																				case 'g':
        																				case 'h':
        																				case 'i':
        																				case 'j':
        																				case 'k':
        																				case 'l':
        																				case 'm':
        																				case 'n':
        																				case 'o':
        																				case 'p':
        																				case 'q':
        																				case 'r':
        																				case 's':
        																				case 't':
        																				case 'u':
        																				case 'v':
        																				case 'w':
        																				case 'x':
        																				case 'y':
        																				case 'z':
        																					{
        																						alt6=12;
        																					}
        																				    break;

        																				default:
        																				    alt6=6;}

        																			}
        																		    break;

        																		default:
        																		    alt6=12;}

        																	}
        																    break;

        																default:
        																    alt6=12;}

        															}
        														    break;

        														default:
        														    alt6=12;}

        													}
        												    break;

        												default:
        												    alt6=12;}

        											}
        										    break;

        										default:
        										    alt6=12;}

        									}
        								    break;
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt6=12;
        									}
        								    break;

        								default:
        								    alt6=5;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 's':
        	{
        		switch ( LA(2) ) 
        		{
        		case 't':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'r':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'u':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'c':
        									{
        										switch ( LA(6) ) 
        										{
        										case 't':
        											{
        												switch ( LA(7) ) 
        												{
        												case '0':
        												case '1':
        												case '2':
        												case '3':
        												case '4':
        												case '5':
        												case '6':
        												case '7':
        												case '8':
        												case '9':
        												case 'A':
        												case 'B':
        												case 'C':
        												case 'D':
        												case 'E':
        												case 'F':
        												case 'G':
        												case 'H':
        												case 'I':
        												case 'J':
        												case 'K':
        												case 'L':
        												case 'M':
        												case 'N':
        												case 'O':
        												case 'P':
        												case 'Q':
        												case 'R':
        												case 'S':
        												case 'T':
        												case 'U':
        												case 'V':
        												case 'W':
        												case 'X':
        												case 'Y':
        												case 'Z':
        												case '_':
        												case 'a':
        												case 'b':
        												case 'c':
        												case 'd':
        												case 'e':
        												case 'f':
        												case 'g':
        												case 'h':
        												case 'i':
        												case 'j':
        												case 'k':
        												case 'l':
        												case 'm':
        												case 'n':
        												case 'o':
        												case 'p':
        												case 'q':
        												case 'r':
        												case 's':
        												case 't':
        												case 'u':
        												case 'v':
        												case 'w':
        												case 'x':
        												case 'y':
        												case 'z':
        													{
        														alt6=12;
        													}
        												    break;

        												default:
        												    alt6=7;}

        											}
        										    break;

        										default:
        										    alt6=12;}

        									}
        								    break;

        								default:
        								    alt6=12;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'l':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'a':
        					{
        						switch ( LA(4) ) 
        						{
        						case 's':
        							{
        								switch ( LA(5) ) 
        								{
        								case 's':
        									{
        										switch ( LA(6) ) 
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=12;
        											}
        										    break;

        										default:
        										    alt6=8;}

        									}
        								    break;

        								default:
        								    alt6=12;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 'A':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'r':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'r':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'a':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'y':
        									{
        										switch ( LA(6) ) 
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=12;
        											}
        										    break;

        										default:
        										    alt6=9;}

        									}
        								    break;

        								default:
        								    alt6=12;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'i':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'e':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'l':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'd':
        									{
        										switch ( LA(6) ) 
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt6=12;
        											}
        										    break;

        										default:
        										    alt6=10;}

        									}
        								    break;

        								default:
        								    alt6=12;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 'p':
        	{
        		switch ( LA(2) ) 
        		{
        		case 'r':
        			{
        				switch ( LA(3) ) 
        				{
        				case 'o':
        					{
        						switch ( LA(4) ) 
        						{
        						case 'p':
        							{
        								switch ( LA(5) ) 
        								{
        								case 'e':
        									{
        										switch ( LA(6) ) 
        										{
        										case 'r':
        											{
        												switch ( LA(7) ) 
        												{
        												case 't':
        													{
        														switch ( LA(8) ) 
        														{
        														case 'y':
        															{
        																switch ( LA(9) ) 
        																{
        																case '0':
        																case '1':
        																case '2':
        																case '3':
        																case '4':
        																case '5':
        																case '6':
        																case '7':
        																case '8':
        																case '9':
        																case 'A':
        																case 'B':
        																case 'C':
        																case 'D':
        																case 'E':
        																case 'F':
        																case 'G':
        																case 'H':
        																case 'I':
        																case 'J':
        																case 'K':
        																case 'L':
        																case 'M':
        																case 'N':
        																case 'O':
        																case 'P':
        																case 'Q':
        																case 'R':
        																case 'S':
        																case 'T':
        																case 'U':
        																case 'V':
        																case 'W':
        																case 'X':
        																case 'Y':
        																case 'Z':
        																case '_':
        																case 'a':
        																case 'b':
        																case 'c':
        																case 'd':
        																case 'e':
        																case 'f':
        																case 'g':
        																case 'h':
        																case 'i':
        																case 'j':
        																case 'k':
        																case 'l':
        																case 'm':
        																case 'n':
        																case 'o':
        																case 'p':
        																case 'q':
        																case 'r':
        																case 's':
        																case 't':
        																case 'u':
        																case 'v':
        																case 'w':
        																case 'x':
        																case 'y':
        																case 'z':
        																	{
        																		alt6=12;
        																	}
        																    break;

        																default:
        																    alt6=11;}

        															}
        														    break;

        														default:
        														    alt6=12;}

        													}
        												    break;

        												default:
        												    alt6=12;}

        											}
        										    break;

        										default:
        										    alt6=12;}

        									}
        								    break;

        								default:
        								    alt6=12;}

        							}
        						    break;

        						default:
        						    alt6=12;}

        					}
        				    break;

        				default:
        				    alt6=12;}

        			}
        		    break;

        		default:
        		    alt6=12;}

        	}
            break;
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'd':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'q':
        case 'r':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt6=12;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt6=13;
        	}
            break;
        case '"':
        	{
        		alt6=14;
        	}
            break;
        case '[':
        	{
        		alt6=15;
        	}
            break;
        case ']':
        	{
        		alt6=16;
        	}
            break;
        case '/':
        	{
        		alt6=17;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt6=18;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 6;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;
        }

        switch (alt6) 
        {
    	case 1:
    	    // D:\\message\\ParseXml.g:1:10: T__18
    	    {
    	        /* 1:10: T__18 */
    	        mT__18(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 2:
    	    // D:\\message\\ParseXml.g:1:16: T__19
    	    {
    	        /* 1:16: T__19 */
    	        mT__19(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 3:
    	    // D:\\message\\ParseXml.g:1:22: T__20
    	    {
    	        /* 1:22: T__20 */
    	        mT__20(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 4:
    	    // D:\\message\\ParseXml.g:1:28: T__21
    	    {
    	        /* 1:28: T__21 */
    	        mT__21(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 5:
    	    // D:\\message\\ParseXml.g:1:34: T_ENUM
    	    {
    	        /* 1:34: T_ENUM */
    	        mT_ENUM(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 6:
    	    // D:\\message\\ParseXml.g:1:41: T_ENUM_FIELD
    	    {
    	        /* 1:41: T_ENUM_FIELD */
    	        mT_ENUM_FIELD(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 7:
    	    // D:\\message\\ParseXml.g:1:54: T_STRUCT
    	    {
    	        /* 1:54: T_STRUCT */
    	        mT_STRUCT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 8:
    	    // D:\\message\\ParseXml.g:1:63: T_CLASS
    	    {
    	        /* 1:63: T_CLASS */
    	        mT_CLASS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 9:
    	    // D:\\message\\ParseXml.g:1:71: T_ARRAY
    	    {
    	        /* 1:71: T_ARRAY */
    	        mT_ARRAY(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 10:
    	    // D:\\message\\ParseXml.g:1:79: T_FIELD
    	    {
    	        /* 1:79: T_FIELD */
    	        mT_FIELD(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 11:
    	    // D:\\message\\ParseXml.g:1:87: T_PROPERTY
    	    {
    	        /* 1:87: T_PROPERTY */
    	        mT_PROPERTY(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 12:
    	    // D:\\message\\ParseXml.g:1:98: T_ID
    	    {
    	        /* 1:98: T_ID */
    	        mT_ID(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 13:
    	    // D:\\message\\ParseXml.g:1:103: T_INT
    	    {
    	        /* 1:103: T_INT */
    	        mT_INT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 14:
    	    // D:\\message\\ParseXml.g:1:109: T_PROP_STRING
    	    {
    	        /* 1:109: T_PROP_STRING */
    	        mT_PROP_STRING(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 15:
    	    // D:\\message\\ParseXml.g:1:123: T_PROPERPTY_BEGIN
    	    {
    	        /* 1:123: T_PROPERPTY_BEGIN */
    	        mT_PROPERPTY_BEGIN(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 16:
    	    // D:\\message\\ParseXml.g:1:141: T_PROPERPTY_END
    	    {
    	        /* 1:141: T_PROPERPTY_END */
    	        mT_PROPERPTY_END(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 17:
    	    // D:\\message\\ParseXml.g:1:157: T_COMMENT
    	    {
    	        /* 1:157: T_COMMENT */
    	        mT_COMMENT(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;
    	case 18:
    	    // D:\\message\\ParseXml.g:1:167: T_WS
    	    {
    	        /* 1:167: T_WS */
    	        mT_WS(ctx ); 
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }


    	    }
    	    break;

        }
    }

    
    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */ 


/* End of code
 * =============================================================================
 */
